# Generated by Django 3.1.1 on 2022-05-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('city', models.CharField(max_length=25)),
                ('zipcode', models.IntegerField(max_length=6, unique=True)),
            ],
        ),
    ]
