# Generated by Django 3.1.1 on 2022-05-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='zipcode',
            field=models.IntegerField(max_length=6),
        ),
    ]
